#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor -d I II III IV V VI VII

bspc config border_width        1
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#3b4252"
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config external_rules_command   ~/.config/bspwm/external-rules.sh
bspc rule -a Firefox desktop='I'
bspc rule -a ncmpcpp desktop='VI'
bspc rule -a Discord desktop='IV'
bspc rule -a Zathura state=tiled
bspc rule -a Fluffychat state=tiled

polybar example &
nitrogen --restore
