[window]
decorations = "None"
startup_mode = "Maximized"

[bell]
animation = "EaseOut"
duration = 50
color = "#404040"

[font]
size = 18
normal = { family = "Terminus", style = "Regular" }
bold = { style = "Bold" }
# italic = { style = "Italic" }
# bold_italic = { style = "Bold Italic" }
